# Advance House Price Prediction Using Pytorch

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("houseprice.csv",usecols=["SalePrice","MSSubClass","MSZoning",
                                        "LotFrontage","LotArea","Street","YearBuilt","LotShape","1stFlrSF",
                                        "2ndFlrSF"]).dropna()

In [3]:
df.shape

(1201, 10)

In [4]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0          60       RL         65.0     8450   Pave      Reg       2003   
1          20       RL         80.0     9600   Pave      Reg       1976   
2          60       RL         68.0    11250   Pave      IR1       2001   
3          70       RL         60.0     9550   Pave      IR1       1915   
4          60       RL         84.0    14260   Pave      IR1       2000   

   1stFlrSF  2ndFlrSF  SalePrice  
0       856       854     208500  
1      1262         0     181500  
2       920       866     223500  
3       961       756     140000  
4      1145      1053     250000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   object 
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   object 
 5   LotShape     1201 non-null   object 
 6   YearBuilt    1201 non-null   int64  
 7   1stFlrSF     1201 non-null   int64  
 8   2ndFlrSF     1201 non-null   int64  
 9   SalePrice    1201 non-null   int64  
dtypes: float64(1), int64(6), object(3)
memory usage: 103.2+ KB


In [6]:
for i in df.columns:
    print("Column name {} and unique values are {}".format(i,len(df[i].unique())))

Column name MSSubClass and unique values are 15
Column name MSZoning and unique values are 5
Column name LotFrontage and unique values are 110
Column name LotArea and unique values are 869
Column name Street and unique values are 2
Column name LotShape and unique values are 4
Column name YearBuilt and unique values are 112
Column name 1stFlrSF and unique values are 678
Column name 2ndFlrSF and unique values are 368
Column name SalePrice and unique values are 597


In [9]:
# chossingc categorical values of columns having less unique values:
import datetime
yearNow=datetime.datetime.now().year

In [10]:
df["Total Years"]=yearNow-df["YearBuilt"]

In [11]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0          60       RL         65.0     8450   Pave      Reg       2003   
1          20       RL         80.0     9600   Pave      Reg       1976   
2          60       RL         68.0    11250   Pave      IR1       2001   
3          70       RL         60.0     9550   Pave      IR1       1915   
4          60       RL         84.0    14260   Pave      IR1       2000   

   1stFlrSF  2ndFlrSF  SalePrice  Total Years  
0       856       854     208500           22  
1      1262         0     181500           49  
2       920       866     223500           24  
3       961       756     140000          110  
4      1145      1053     250000           25

In [14]:
df.drop("YearBuilt",axis=1,inplace=True)

In [15]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  1stFlrSF  \
0          60       RL         65.0     8450   Pave      Reg       856   
1          20       RL         80.0     9600   Pave      Reg      1262   
2          60       RL         68.0    11250   Pave      IR1       920   
3          70       RL         60.0     9550   Pave      IR1       961   
4          60       RL         84.0    14260   Pave      IR1      1145   

   2ndFlrSF  SalePrice  Total Years  
0       854     208500           22  
1         0     181500           49  
2       866     223500           24  
3       756     140000          110  
4      1053     250000           25

In [17]:
## categorical features
cat_features=["MSSubClass","MSZoning","LotShape","Street"]
out_feature="SalePrice"

In [18]:
df["MSSubClass"].unique()

array([ 60,  20,  70,  50, 190,  45,  90, 120,  30,  80, 160,  75, 180,
        40,  85], dtype=int64)

In [19]:
from sklearn.preprocessing import LabelEncoder
lbl_encoders={}
lbl_encoders["MSSubClass"]=LabelEncoder()
lbl_encoders["MSSubClass"].fit_transform(df["MSSubClass"])

array([5, 0, 5, ..., 6, 0, 0], dtype=int64)

In [21]:
lbl_encoders

{'MSSubClass': LabelEncoder()}

In [25]:
from sklearn.preprocessing import LabelEncoder
lbl_encoders={}
for feature in cat_features:
   lbl_encoders[feature]=LabelEncoder()
   df[feature]=lbl_encoders[feature].fit_transform(df[feature])


In [30]:
#stacking and converting into tensors:
cat_features=np.stack([df["MSSubClass"],df["MSZoning"],df["Street"],
                      df["LotShape"]],axis=1)
cat_features

array([[5, 3, 1, 3],
       [0, 3, 1, 3],
       [5, 3, 1, 0],
       ...,
       [6, 3, 1, 3],
       [0, 3, 1, 3],
       [0, 3, 1, 3]], dtype=int64)

In [31]:
# convert numpy to Tensors
import torch
cat_features=torch.tensor(cat_features,dtype=torch.int64)
cat_features

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [ ]:
## create continous variable

